### ISSUE TITLE
Health Check JSON shows healthy, HTTP response code is 500

### ISSUE THREAD

**Issue by isuftin** [USGS-CIDA/coastal-hazards#1597]
Issue stems from this code: https://github.com/USGS-CIDA/coastal-hazards/blob/master/coastal-hazards-portal/src/main/java/gov/usgs/cida/coastalhazards/rest/data/HealthResource.java

NAGIOS is puking repeatedly.

```
$ curl 'https://marine.usgs.gov/coastalchangehazardsportal/data/health/' -i
HTTP/1.1 500 Internal Server Error
Date: Sat, 20 May 2017 23:23:16 GMT
Content-Type: application/json
Content-Length: 205
Set-Cookie: JSESSIONID=794CC17BB5040126814D3478534E86FC.default; Path=/coastalchangehazardsportal; Secure; HttpOnly
X-FRAME-OPTIONS: SAMEORIGIN
Set-Cookie: BNES_JSESSIONID=somethingsomethingsomething; Path=/coastalchangehazardsportal; Secure; HttpOnly
Strict-Transport-Security:  max-age=31536000

{"DefaultGson":true,"EntityManagerFactory":true,"Geoserver":{"configured":true,"up":true},"ItemManager":true,"NonSubtreeGson":true,"PyCsw":{"getCapabilities":true},"SubtreeGson":true,"TileCacheStale":true}
```

**Comment by isuftin** [comment]
Tomcat logs do not show any warnings. This means that throughout the code, no exceptions are hit but the `overallHealth` variable comes into the block https://github.com/USGS-CIDA/coastal-hazards/blob/master/coastal-hazards-portal/src/main/java/gov/usgs/cida/coastalhazards/rest/data/HealthResource.java#L212-L217 as false

**Comment by thongsav-usgs** [comment]
Word of caution, I've encountered several try-finally blocks that seem to swallow exceptions in the project.

**Comment by mhines-usgs** [comment]
This was caught and fixed. closing.
